version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Saigon'
    reviewers:
      - 'hckhanh'
    commit-message:
      prefix: 'deps'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Saigon'
    reviewers:
      - 'hckhanh'
    commit-message:
      prefix: 'build'
