version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    timezone: "Asia/Saigon"
  open-pull-requests-limit: 10
  reviewers:
  - "hckhanh"
  commit-message:
    prefix: "deps"
    include: "scope"
