language: node_js
os:
  - linux
  - osx
node_js:
  - 'lts/*'
  - 'node'
cache:
  directories:
  - ~/.npm
  - ~/.cache
  - node_modules
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
