language: node_js
os:
  - linux
  - osx
node_js:
  - '6'
  - 'lts/*'
  - 'node'
cache:
  directories:
  - ~/.npm
  - ~/.cache
  - node_modules
jobs:
  include:
  - stage: npm release
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
