language: node_js
os:
  - linux
  - osx
node_js:
  - '6'
  - 'lts/*'
  - 'node'
cache:
  directories:
  - ~/.npm
  - ~/.cache
  - node_modules
jobs:
  include:
    - stage: npm release
      if: branch = master
      node_js: 'node'
      script:
        - npm run build:cjs
        - npm run build:es6
        - npm run build:esnext
        - npm run build:amd
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
