name: Publish GPR Package

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v2.5.2
        with:
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - name: Build commonjs, es6, esnext and amd
        run: |
          pnpm build:cjs
          pnpm build:es
          pnpm build:types
      - name: Publish to gpr
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
