name: Publish GPR Package

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: 12
          check-latest: true
          registry-url: https://npm.pkg.github.com/
      - name: Build commonjs, es6, esnext and amd
        run: |
          yarn build:cjs
          yarn build:es
          yarn build:types
      - name: Publish to gpr
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
