name: Publish JSR Package

on:
  release:
    types: [published]

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v2.1.4
        with:
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - name: Build commonjs, es6, esnext and amd
        run: |
          pnpm build:cjs
          pnpm build:es
          pnpm build:types
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Update version in deno.json
        run: |
          VERSION_NUMBER="$(node -p "require('./package.json').version")"
          jq '.version = "'$VERSION_NUMBER'"' deno.json > temp.json
          mv temp.json deno.json
      - name: Install Deno
        uses: denoland/setup-deno@v1.1.4
      - name: Publish to jsr
        run: deno publish
