name: Publish NPM Package

on:
  push:
    branches: [master]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  publish-npm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - name: Build commonjs, es6, esnext and amd
        run: |
          yarn build:cjs
          yarn build:es
          yarn build:types
      - name: Publish to npm
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
