name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Build commonjs, es6, esnext and amd
        run: |
          npm run build:cjs
          npm run build:es6
          npm run build:esnext
          npm run build:amd
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
