name: Publish NPM Package

on:
  push:
    branches: [master]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  publish-npm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v2.1.4
        with:
          cache: 'pnpm'
      - name: Build commonjs, es6, esnext and amd
        run: |
          pnpm build:cjs
          pnpm build:es
          pnpm build:types
      - name: Publish to npm
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
