name: Publish NPM Package

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Check eslint and unit tests
        run: npm cit
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build commonjs, es6, esnext and amd
        run: |
          npm run build:cjs
          npm run build:es6
          npm run build:esnext
          npm run build:amd
      - name: Publish to npm
        if: github.event.action == 'published'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to gpr
          if: github.event.action == 'published'
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
