name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'stale'
