name: Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@master
        with:
          node-version: 12
          check-latest: true
      - name: Dependency check
        run: npm ci
      - name: Dependency cruiser check
        run: npm run test:deps
      - name: Prettier check
        run: npm run test:prettier
      - name: ESLint check
        run: npm run test:eslint
  test:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        node: [12, 13, 14]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node}}
      - name: Unit tests
        run: npm cit
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12
          check-latest: true
      - name: Download CodeClimade Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Generate coverage report
        run: npx nyc npm cit
      - name: Upload coverage report
        if: success()
        run: ./cc-test-reporter after-build --exit-code 0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
