name: Tests

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - name: Dependency check
        run: yarn --immutable --immutable-cache --check-cache
      - name: Dependency cruiser check
        run: yarn test:deps
      - name: Prettier check
        run: yarn test:prettier
      - name: ESLint check
        run: yarn test:eslint
      - name: Skypack check
        run: yarn test:skypack
  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 21]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Node.js ${{matrix.node}}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{matrix.node}}
      - name: Unit tests
        run: yarn test
