name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          check-latest: true
      - name: Dependency check
        run: npm ci
      - name: Dependency cruiser check
        run: npm run test:deps
      - name: Prettier check
        run: npm run test:prettier
      - name: ESLint check
        run: npm run test:eslint
      - name: Skypack check
        run: npm run test:skypack
  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 13, 14, 15]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Node.js ${{matrix.node}}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{matrix.node}}
      - name: Unit tests
        run: npm cit
