name: Tests

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v2.1.4
        with:
          cache: 'pnpm'
      - name: Dependency check
        run: pnpm --immutable
      - name: Dependency cruiser check
        run: pnpm test:deps
      - name: Prettier check
        run: pnpm test:prettier
      - name: ESLint check
        run: pnpm test:eslint
      - name: Skypack check
        run: pnpm test:skypack
  test:
    needs: lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 21]
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: pnpm/action-setup@v3.0.0
      - name: Set up Node.js ${{matrix.node}}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
      - name: Unit tests
        run: pnpm test
